### PR TITLE
Changes for PostgreSQL 11

### PR DESCRIPTION
**Pull request by dverite**
- AllocSetContextCreate() becomes AllocSetContextCreateExtended().
- ACL_KIND_CLASS replaced by OBJECT_TABLE in aclcheck_error().
- BackgroundWorkerInitializeConnection() takes a new flag parameter.

### CODE REVIEW

**Comment by marcocitus** [comment]
Thanks! Merged this into `master`.

**Comment by ChristophBerg** [comment]
@marcocitus: could you tag a new release with this fix so I can update the Debian package? Thanks!

**Comment by marcocitus** [comment]
@ChristophBerg Tagged: https://github.com/citusdata/pg_cron/releases/tag/v1.1.2

**Comment by ChristophBerg** [comment]
Thanks!

**Pull request closed without merging**
