### PR TITLE
The smallest unit that supports pg_cron is the granularity of seconds…

### PR DESCRIPTION
**Pull request by TsinghuaLucky912**
…. If you need to contact me, my email: 2903807914@qq.com comes from Xi’an, China. Thanks

E.g：

postgres=# SELECT cron.schedule('hasname', '*/30 * * * * *', 'select * from pg_extension');
 schedule 

        1
(1 row)

postgres=#                                                                                 
2021-09-08 14:43:30.005 CST [58336] LOG:  cron job 1 starting: select * from pg_extension
2021-09-08 14:43:30.091 CST [58336] LOG:  cron job 1 completed: 2 rows
2021-09-08 14:44:00.004 CST [58336] LOG:  cron job 1 starting: select * from pg_extension
2021-09-08 14:44:00.095 CST [58336] LOG:  cron job 1 completed: 2 rows

### CODE REVIEW

**Review by marcocitus — COMMENTED** [review]
I like how simple the change is, though it would break all existing pg_cron installations since the old schedule syntax is not accepted, so I cannot really merge it. Is there a way to do this in a backwards compatible way?

**Comment by TsinghuaLucky912** [comment]
> I like how simple the change is, though it would break all existing pg_cron installations since the old schedule syntax is not accepted, so I cannot really merge it. Is there a way to do this in a backwards compatible way?

My idea is to extend the functions of the existing pg_cron, because many people have such a need in many scenarios. And I also know that there is no such grammar for crondb. I don’t understand the following sentence very well?

Is there a way to do this in a backwards compatible way?

**Comment by TsinghuaLucky912** [comment]
Excuse me, do you mean that both of the following can work normally?

// 2min
SELECT cron.schedule('*/2 * * * *', 'insert into mytable values (now())'); 

// 20sec
SELECT cron.schedule('*/20 * * * * *', 'insert into mytable values (now())'); 

If this is the case, I think about this plan again,thank you

**Comment by marcocitus** [comment]
> Excuse me, do you mean that both of the following can work normally?

Yes. Otherwise updating pg_cron to this branch breaks all existing jobs and all existing scripts that call cron.schedule.

I do have some other high-level concerns about second granularity:
- Schedule syntax becomes (even) harder to use. What if we just support an `interval '1 second'` as an alternative to cron syntax?
- cron.log_run_details can grow much faster. Do we need automatic clean up?
- We inherited some logic for dealing with clock jumps from Vixie cron, which may need to be adjusted for second granularity.
- A job starting before the last execution is finished will become much more frequent. Do we need to adjust our policy?

**Comment by TsinghuaLucky912** [comment]
First of all, it will indeed destroy the existing use, and there may be a certain cost loss.

Because the subsequent time interval is too short, additional unnecessary loss will occur. Even in the process of execution, log_run_details will continue to be inserted (updated). This may be a problem.

Now the original minute logic has been modified (but the clock jump block is actually still minutes)

In my opinion, being willing and willing is mainly based on the needs of the scene, of course, this only represents my own opinion, thank you

---------------------------------------------------------

If the problem you mentioned is very unacceptable, then I will close this application. In any case, I have benefited a lot from your opinion. Next, I will consider this plan again. thank you all

**Comment by TsinghuaLucky912** [comment]
First of all, it will indeed destroy the existing use, and there may be a certain cost loss.

Because the subsequent time interval is too short, additional unnecessary loss will occur. Even in the process of execution, log_run_details will continue to be inserted (updated). This may be a problem.

Now the original minute logic has been modified (but the clock jump block is actually still minutes)

In my opinion, being willing and willing is mainly based on the needs of the scene, of course, this only represents my own opinion, thank you

---------------------------------------------------------

If the problem you mentioned is very unacceptable, then I will close this application. In any case, I have benefited a lot from your opinion. Next, I will consider this plan again. thank you all

**Comment by TsinghuaLucky912** [comment]
My plan is not mature yet, the pull is now closed.

Thank you for your opinion. I will think about it again. Maybe we can reach a consensus next time. Thank you.

Best wishes from ancient China

**Pull request closed without merging**
